### ISSUE TITLE
DISABLE_COOKIE is not supported for PATCH request

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/wso2-axis2#211]
**Description:**
DISABLE_COOKIE is not supported for PATCH request

Related issue: wso2/product-ei#4430
Related doc task: https://github.com/wso2/docs-ei/issues/1600

**Comment by milindaperera** [comment]
We should create git issues in product repositories product-ei or micro-integrator otherwise we lose track when releasing the product

**Comment by dilini-muthumala** [comment]
@milindaperera Noted. Closing this issue, as this can be tracked via https://github.com/wso2/product-ei/issues/4430
